baseURL = 'https://mi-ki-ri.github.io/official-2021/'
languageCode = 'en-us'
title = 'Mikirihassha P Official 2021~'
theme = "2021"
publishDir = "docs"

[outputs]
home = ["HTML", "JSON", "RSS"]
section = ["JSON"]
page = [  "HTML", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"